### ISSUE TITLE
Wow ... a tool I would love to have

### ISSUE THREAD

**Issue by codemedic** [andriyko/browser-dispatcher#21]
Sorry; I am making a feature request. So I am not posting based on the template.

This app .. superb idea.

I have been using [a bash script](https://github.com/codemedic/bash-ninja/blob/master/open-url) to get some of the functionality.

If you could make this available on Linux, that would be wonderful!

**Comment by andriyko** [comment]
Closing this feature request. The project was initially planned as macOS only app.
