### ISSUE TITLE
Run in background on system startup

### ISSUE THREAD

**Issue by gustavobittencourt** [andriyko/browser-dispatcher#24]
Hi Andriy!

First of all, congratulations for this amazing app.

When the application is first opened, either at the beginning of the system or the first time a URL is clicked, the BrowserDispatcher GUI also opens in the foreground. As I have already set up the dispatches I need, I wonder if it's possible to have this process starting transparently in the background, without the GUI showing up.

Thank you!

Regards,

Gustavo

**Comment by andriyko** [comment]
@gustavobittencourt , I am not sure I understood the issue correctly. The UI will show up when the system starts (if `Open at login` option is selected):
<img width="355" alt="screenshot 2018-08-03 23 49 09" src="https://user-images.githubusercontent.com/719450/43665231-3b13b73c-9778-11e8-8f8d-2d372089962c.png">

Then, you can close the app window, the app will run in the background.

Regarding

> the first time a URL is clicked, the BrowserDispatcher GUI also opens in the foreground

Please check `Use default browser (do not show selector)` option

<img width="568" alt="screenshot 2018-08-03 23 47 32" src="https://user-images.githubusercontent.com/719450/43665162-f948865c-9777-11e8-9d57-99bfb30fcbba.png">

**Comment by gustavobittencourt** [comment]
> The UI will show up when the system starts (if Open at login option is selected)
> Then, you can close the app window, the app will run in the background.

Yes. What I wanna know is if I can disable the UI for showing up when the system starts, avoiding the need to close the window to have the app running in the background.

Maybe it can be achieved by loading just the agent on system startup, and not the whole UI, but I don't know if these components (the agent and the UI) are decoupled from each other.

Thank you again!

**Comment by andriyko** [comment]
Got it. I did not realize that UI showing up when the system starts may be annoying because I turn off my laptop once per N weeks. The issue can be categorized as an improvement. Unfortunately, I can't work on that right now. @gustavobittencourt , PRs are welcome:)
